version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=localhost
        restart: always
        depends_on:
            - php
    php:
        image: php:7.4-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"